### PR TITLE
Run tests on PHP 8.3 and update test suite

### PR DESCRIPTION
**Pull request by yadaiio**
This pull request builds on top of #11.

References: https://github.com/reactphp/socket/pull/300, https://github.com/clue/reactphp-zenity/pull/63, https://github.com/clue/reactphp-csv/pull/33 and others.

### CODE REVIEW

**Review by SimonFrings — CHANGES_REQUESTED** [review]
@yadaiio Thanks for filing this PR, can you also adjust the `composer.json` similar to how you did in [clue/reactphp-multicast](https://github.com/clue/reactphp-multicast/pull/22/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34)?

**Comment by yadaiio** [comment]
Thank you @SimonFrings for noticing this. Should be fixed now 😉

**Review by SimonFrings — APPROVED** [review]
Thanks for changes, looks good :+1:

**Review by clue — APPROVED** [review]
@yadaiio Thanks for the update, changes LGTM! :shipit:

**Pull request merged**
